language: cpp
dist: trusty
install: ninja

before_script:
- mkdir build
- cd build
#
# Update / Install CMake
#
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir -p external/cmake
    pushd external/cmake
    wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
    chmod +x cmake-*-Linux-x86_64.sh
    ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
    export PATH="${PWD}/bin:$PATH"
    popd
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
  fi
# matrix:
#  include:
#    - os: linux
#    env:
#      - TEST="Unit Tests"
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#          - llvm-toolchain-trusty-5.0
#        packages:
#          - clang-5.0
#          - clang-tidy-5.0
#          - gcc-7
#          - g++-7
script:
- mkdir bin_test
- cd bin_test
- cmake .. -DCLANG_TIDY=ON -DBUILD_TESTS=ON -DARCH=X86 -GNinja
- ninja
- test/UT/eul_tests
