name: EmbeddedUtilityLibraries Unit Tests
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Symbitic/install-cmake@v0.1.0
    - name: configure
      run: mkdir bin && cd bin && cmake -DCMAKE_BUILD_TYPE=Release
    - name: make unit tests
      run: ninja run_eul_ut
