name: ClangTidy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake python3 python3-pip clang-tidy gcc-10 g++-10 
        sudo pip3 install virtualenv
    - uses: actions/checkout@v2
    - name: configure & execute tests
      run: |
        rm -rf bin && mkdir bin && cd bin && cmake .. -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=debug
        run-clang-tidy

