name: ClangTidy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake python3 python3-pip clang-tidy
        sudo pip3 install virtualenv
    - uses: actions/checkout@v2
    - name: configure & execute tests
      run: |
        rm -rf bin && mkdir bin && cd bin && cmake .. -DCLANG_TIDY=ON -DCMAKE_BUILD_TYPE=Release -GNinja
        run-clang-tidy -p bin

