name: Publish GithubPages
on:
  push:
    branches:
    - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.4
      with:
        doxyfile-path: ./docs/doxygen/Doxyfile-prj.cfg
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages