name: Sanitizers - UT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ut_sanitizers:
    name: UT sanitizer - ${{ matrix.sanitizers.name }} 
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/matgla/eul_ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    strategy:
      fail-fast: false
      matrix:
        sanitizers: 
        - {
            flag: "ENABLE_ASAN",
            name: "AddressSanitizer"
          }
        - {
            flag: "ENABLE_LSAN", 
            name: "LeakSanitizer"
          }
        - {
            flag: "ENABLE_UBSAN",
            name: "UndefinedBehaviourSanitizer"
          }
        - {
            flag: "ENABLE_TSAN",
            name: "ThreadSanitizer"
          }
    steps:
      - uses: actions/checkout@v2
      - name: Print Environment
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Configure Environment
        shell: bash 
        run: |
            mkdir build
      - name: Configure project
        shell: bash
        working-directory: build
        run: |
          cmake .. -D${{ matrix.sanitizers.flag }}=ON -GNinja
      - name: Build & Execute UT
        shell: bash 
        working-directory: build
        run: ninja check

