name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ut:
    name: ${{ matrix.config.name }} 
    runs-on: ${{ matrix.config.os }} 
    strategy:
      fail-fast: false
      matrix:
        config: 
        - { 
            name: "Ubuntu 20.04 GCC",
            os: ubuntu-20.04,
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generator: "Ninja"
          }
        - {
            name: "Ubuntu 20.04 Clang",
            os: ubuntu-20.04,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generator: "Ninja"
          }
    container: 
      image: ghcr.io/matgla/eul_ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v2
      - name: Print Environment
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Configure Tests
        shell: bash 
        run: |
          mkdir build 
          cd build && cmake .. -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -G "${{ matrix.config.generator }}"
      - name: Run UT
        shell: bash 
        working-directory: build 
        run: ninja check