name: ContinousIntegration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ut:
    runs-on: ubuntu-20.04
    steps:
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++-10 gcc-10 ninja-build python3 python3-pip
        sudo pip3 install virtualenv
    - uses: actions/checkout@v2
    - name: configure & execute tests
      run: |
        rm -rf bin && mkdir bin && cd bin && cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja
        ninja run_eul_ut

