name: SonarQube - UT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ut_sonar:
    runs-on: ubuntu-latest
    env: 
      SONAR_SCANNER_VERSION: 4.7.0.2747
      SONAR_SERVER_URL: "https://sonarcloud.io"
    container: 
      image: ghcr.io/matgla/eul_ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v2
      - name: Show toolchain versions
        shell: bash
        run: | 
          cmake --version
          gcc --version
      - name: Prepare environment 
        shell: bash 
        run: |
          mkdir build
      - name: Generate CMake
        shell: bash 
        working-directory: build
        run: | 
          cmake .. -GNinja
      - name: Execute SonarScanner 
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.host.url="${{ env.SONAR_SERVER_URL }}" --define sonar.cfamily.compile-commands="build/compile_commands.json"

          
