name: UnitTests - MSVC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ut_windows:
    name: "Windows MSVC"
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Print Environment
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install dependencies on Windows 
        run: | 
          choco install ninja cmake python3 pip
          ninja --version 
          cmake --version
      - name: Install VirtualEnv Windows 
        run: |
            pip3.exe install virtualenv
      - name: Configure Tests
        shell: bash 
        run: |
          mkdir build 
          cd build && cmake .. -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 17 2022"
      - name: Build UT 
        shell: bash 
        working-directory: build
        run: cmake --build . --config Release
      - name: Run UT
        shell: bash 
        working-directory: build 
        run: ctest --output-on-failure